version: '3.7'

volumes:
  media:
  static:
  pgdata:

networks:
  netbox:
  db:
  auth:
  web:
    external: true

services:
  frontend:
    image: localhost:5000/netbox/frontend
    build: nginx
    volumes:
      - 'media:/usr/share/nginx/html/media:ro'
      - 'static:/usr/share/nginx/html/static:ro'
    networks:
      - auth
      - netbox
  backend:
    image: nomaster/netbox
    volumes:
      - 'media:/opt/netbox/media'
      - 'static:/opt/netbox/static'
    networks:
      - db
      - netbox
    environment:
      - NETBOX_SECRET
      - NETBOX_TIME_ZONE
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: netbox
      POSTGRES_USER: netbox
    networks:
      - db
  oauth2_proxy:
    image: localhost:5000/netbox/oauth2_proxy
    build: oauth2_proxy
    networks:
      - auth
      - web
    environment:
      - OAUTH2_PROXY_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET
      - OAUTH2_PROXY_COOKIE_SECRET
    deploy:
      labels:
        - 'traefik.docker.network=web'
        - 'traefik.frontend.rule=Host:netbox.nomaster.cc'
        - 'traefik.enable=true'
        - 'traefik.port=80'
